-- db/changelog/sql/db.changelog-insert-spaceship-data.sql

INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Millennium Falcon', 'Star Wars', 1977);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('USS Enterprise', 'Star Trek', 1966);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Serenity', 'Firefly', 2002);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('TARDIS', 'Doctor Who', 1963);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Discovery One', '2001: A Space Odyssey', 1968);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Eagle Transporter', 'Space: 1999', 1975);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Nostromo', 'Alien', 1979);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Red Dwarf', 'Red Dwarf', 1988);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Bebop', 'Cowboy Bebop', 1998);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Event Horizon', 'Event Horizon', 1997);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Galactica', 'Battlestar Galactica', 1978);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Andromeda Ascendant', 'Andromeda', 2000);
INSERT INTO SPACESHIP (SPACESHIP_NAME, MOVIE_NAME, MOVIE_YEAR) VALUES ('Razor Crest', 'The Mandalorian', 2019);
